### PR TITLE
chore: compress app's images

### LINKED ISSUE #22: The large size of the images affects the performance of the application
## Current Behavior
The images contained in the current repository are in high resolution resulting in a very large size. Thus, the initial load time of the app to be very slow.

## Expected Behavior
The images can be compressed to reduce their size without losing their quality.

## Steps to Reproduce
- Both images are contained in the `assets` folder and those that are used in the `README.md` file, have a huge size.
- For example, the current size of the `background.png` image is 3.4 MB, while the compressed version of the same image is 859 KB. The size is reduced by 75% without losing quality!

### PR DESCRIPTION
**Pull request by nikosanif**
# Current Behavior
The images contained in the current repository are in high resolution resulting in a very large size. Thus, the initial load time of the app to be very slow.

# Expected Behavior
The images can be compressed to reduce their size without losing their quality. Three images have been affected:
- `preview.png`: from 4.0 MB to 802.9 KB (-80%)
- `src/assets/background.png`: from 3.4 MB to 859 KB (-75%)
- `src/assets/search-bar.png`: from 6.2 KB to 1.9 KB (-70%)

# Related Issues
Fixes #22

### CODE REVIEW

**Comment by bampakoa** [comment]
Thanks very much for your PR @nikosanif 🙏  I am wondering what tool did you use for image compression?

**Comment by nikosanif** [comment]
> Thanks very much for your PR @nikosanif 🙏 I am wondering what tool did you use for image compression?

You are welcome @bampakoa! I used [tinypng](https://tinypng.com/) for image compression.

**Comment by bampakoa** [comment]
@nikosanif dang! You are right! I thought that the PR was adding that file. I haven't noticed it all these time 🙄. Thanks for this catch and for the information about the compression 🙏

**Comment by nikosanif** [comment]
Done! Commit message and PR's name changed.

**Pull request merged**
